---
name: Check 

on:
  workflow_dispatch:
  workflow_call:
  push:

jobs:
  check:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - run: nix flake check
